# Generated by Django 5.2.13 on 2026-06-29 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0008_student_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('TC', 'Transfer Certificate'), ('BONAFIDE', 'Bonafide Certificate'), ('STUDY_CERTIFICATE', 'Study Certificate'), ('BANK_LETTER', 'Bank Letter'), ('LOR', 'Letter of Recommendation'), ('OTHER', 'Other')], max_length=20)),
                ('doc_type_other', models.CharField(blank=True, max_length=160)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='student_documents/')),
                ('approver_remarks', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='admissions.student')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['student', 'status'], name='student_doc_student_ca69f9_idx')],
            },
        ),
    ]
