# Generated by Django 5.2.13 on 2026-05-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('end_date', models.DateField(help_text='When the assignee is expected to finish.')),
                ('assignee_remarks', models.TextField(blank=True, help_text='Notes from the assignee while working on the task.')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Completed')], db_index=True, default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['assignee', 'status'], name='tasks_task_assigne_7928f6_idx'), models.Index(fields=['created_by', 'status'], name='tasks_task_created_69a8b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'assignee'), name='uniq_task_name_per_assignee')],
            },
        ),
    ]
