# Generated by Django 5.2.13 on 2026-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('master', '0002_institute_state_campus_institute_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campuses',
            field=models.ManyToManyField(blank=True, help_text='Campuses this user can act in. Empty = no campus scope assigned.', related_name='users', to='master.campus'),
        ),
    ]
