# Generated by Django 5.2.13 on 2026-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_campuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='If False, the round-robin assigner skips this user.'),
        ),
        migrations.AddField(
            model_name='user',
            name='unavailable_reason',
            field=models.CharField(blank=True, help_text="e.g. 'On leave', 'Out of office', 'Disabled by admin'.", max_length=120),
        ),
    ]
