# Generated by Django 5.2.13 on 2026-04-28 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_reporting_manager_1'),
        ('master', '0002_institute_state_campus_institute_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('LEAVE', 'Leave'), ('ON_DUTY', 'On-duty')], max_length=10)),
                ('half_day_allowed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. 2024-25', max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='CompOffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_date', models.DateField()),
                ('worked_session_1', models.PositiveSmallIntegerField(default=0)),
                ('worked_session_2', models.PositiveSmallIntegerField(default=0)),
                ('count', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reason', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('approver_remarks', models.TextField(blank=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('decided_on', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compoff_decisions', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compoff_applications', to='employees.employee')),
            ],
            options={
                'ordering': ('-applied_on',),
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('is_optional', models.BooleanField(default=False, help_text='Optional / restricted holiday — does not auto-deduct from leave count.')),
                ('campus', models.ForeignKey(blank=True, help_text='Null = applies to all campuses.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='master.campus')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_session', models.PositiveSmallIntegerField(help_text='1=AM, 2=Full day, 3=Permission slot 1, 4=Permission slot 2')),
                ('count', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField()),
                ('manager_email', models.EmailField(help_text="Snapshot at apply-time so RM changes don't reroute.", max_length=254)),
                ('cc_emails', models.CharField(blank=True, max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Cancelled'), (5, 'Withdrawn')], default=1)),
                ('approver_remarks', models.TextField(blank=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('decided_on', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_applications', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='leaves.leavetype')),
            ],
            options={
                'ordering': ('-applied_on',),
            },
        ),
        migrations.CreateModel(
            name='EmailDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=80)),
                ('to', models.CharField(max_length=400)),
                ('cc', models.CharField(blank=True, max_length=400)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('related_compoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='leaves.compoffapplication')),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='leaves.leaveapplication')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=1, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='leaves.leavetype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='leaves.session')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.AddIndex(
            model_name='compoffapplication',
            index=models.Index(fields=['employee', 'status'], name='leaves_comp_employe_ab3b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='compoffapplication',
            index=models.Index(fields=['worked_date'], name='leaves_comp_worked__ffc538_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='leaves_holi_date_f1ed5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('date', 'campus'), name='uniq_holiday_date_campus'),
        ),
        migrations.AddIndex(
            model_name='emaildispatchlog',
            index=models.Index(fields=['status', 'created_at'], name='leaves_emai_status_c437e2_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['employee', 'status'], name='leaves_leav_employe_aa6ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['from_date', 'to_date'], name='leaves_leav_from_da_cbc9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['manager_email'], name='leaves_leav_manager_3a296d_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__gte', models.F('from_date'))), name='leave_app_to_after_from'),
        ),
        migrations.AddIndex(
            model_name='leaveallocation',
            index=models.Index(fields=['employee', 'session'], name='leaves_leav_employe_a67d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveallocation',
            index=models.Index(fields=['leave_type', 'start_date'], name='leaves_leav_leave_t_b85e01_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaveallocation',
            constraint=models.UniqueConstraint(fields=('employee', 'session', 'leave_type', 'start_date', 'end_date'), name='uniq_alloc_per_emp_session_type_window'),
        ),
    ]
