# Generated by Django 5.2.13 on 2026-07-08 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_designation_role'),
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the constraint + index that reference `session` BEFORE the
        # field itself, otherwise SQLite's table rebuild fails trying to
        # recreate a constraint on a column that no longer exists.
        migrations.RemoveConstraint(
            model_name='leaveallocation',
            name='uniq_alloc_per_emp_session_type_window',
        ),
        migrations.RemoveIndex(
            model_name='leaveallocation',
            name='leaves_leav_employe_a67d6c_idx',
        ),
        migrations.RemoveField(
            model_name='leaveallocation',
            name='session',
        ),
        migrations.AddIndex(
            model_name='leaveallocation',
            index=models.Index(fields=['employee', 'leave_type'], name='leaves_leav_employe_5f3fd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaveallocation',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'start_date', 'end_date'), name='uniq_alloc_per_emp_type_window'),
        ),
        # Session FK is gone now, so the model can be dropped.
        migrations.DeleteModel(
            name='Session',
        ),
    ]
