# Generated by Django 5.2.13 on 2026-07-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_remove_leaveallocation_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
