# Generated by Django 5.2.13 on 2026-09-18 07:46

from django.db import migrations, models


ENFORCED = ("CASUAL", "COMP_OFF")


def enable(apps, schema_editor):
    apps.get_model("leaves", "LeaveType").objects.filter(
        code__in=ENFORCED,
    ).update(enforce_balance=True)


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_leaveapplication_status_delete_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='enforce_balance',
            field=models.BooleanField(default=False, help_text='Block applies that exceed granted − availed − pending.'),
        ),
        migrations.RunPython(enable, migrations.RunPython.noop),
    ]
