# Generated by Django 5.2.13 on 2026-09-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leavetype_enforce_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='from_session',
            field=models.PositiveSmallIntegerField(help_text='1=First half, 2=Full day, 3=Permission slot 1, 4=Permission slot 2, 5=Second half'),
        ),
    ]
