# Generated by Django 5.2.13 on 2026-09-30 15:32

from django.db import migrations, models


def backfill_manager_email(apps, schema_editor):
    # Rows filed before the snapshot existed were routed by the live
    # reporting manager — freeze that so pending ones stay visible to
    # the same manager.
    CompOff = apps.get_model("leaves", "CompOffApplication")
    for co in CompOff.objects.select_related(
            "employee__reporting_manager_1").filter(manager_email=""):
        rm = co.employee.reporting_manager_1
        if rm and rm.email_primary:
            co.manager_email = rm.email_primary
            co.save(update_fields=["manager_email"])


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_leave_second_half_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoffapplication',
            name='cc_emails',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='compoffapplication',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.RunPython(backfill_manager_email, migrations.RunPython.noop),
    ]
