# Generated by Django 5.2.13 on 2026-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursewaretopic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courseware/images/'),
        ),
    ]
