# Generated by Django 5.2.13 on 2026-05-01 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_reporting_manager_1'),
        ('master', '0006_coursesubject_subject_coursesubject_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('classroom_conflict_overridden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to='master.batch')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='master.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots_created', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_slots', to='employees.employee')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to='master.subject')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to='master.timeslot')),
            ],
            options={
                'ordering': ('date', 'time_slot__start_time'),
                'indexes': [models.Index(fields=['batch', 'date'], name='academics_s_batch_i_ee4baa_idx'), models.Index(fields=['instructor', 'date'], name='academics_s_instruc_8c7896_idx'), models.Index(fields=['classroom', 'date'], name='academics_s_classro_a1d87d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'SCHEDULED')), fields=('instructor', 'date', 'time_slot'), name='uniq_instructor_date_slot_active'), models.UniqueConstraint(condition=models.Q(('status', 'SCHEDULED')), fields=('batch', 'date', 'time_slot'), name='uniq_batch_date_slot_active')],
            },
        ),
    ]
