# Generated by Django 5.2.13 on 2026-05-01 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='attendance_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='attendance_frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='attendance_frozen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_schedule_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('ON_DUTY', 'On Duty'), ('EXCUSED', 'Excused')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to='academics.scheduleslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to='admissions.student')),
            ],
            options={
                'ordering': ('schedule_slot', 'student'),
                'indexes': [models.Index(fields=['student', 'status'], name='academics_a_student_90dc56_idx'), models.Index(fields=['schedule_slot', 'status'], name='academics_a_schedul_2ff16c_idx')],
                'unique_together': {('schedule_slot', 'student')},
            },
        ),
    ]
