# Generated by Django 5.2.13 on 2026-05-01 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_scheduleslot_attendance_frozen_and_more'),
        ('admissions', '0002_initial'),
        ('master', '0006_coursesubject_subject_coursesubject_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_marks', models.DecimalField(decimal_places=1, max_digits=5)),
                ('due_date', models.DateTimeField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('is_published', models.BooleanField(default=True, help_text="When False, students don't see the assignment.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='master.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='master.subject')),
            ],
            options={
                'ordering': ('-due_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('text_response', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('extended_due_date', models.DateTimeField(blank=True, help_text='Per-student deadline override.', null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('LATE', 'Late submission'), ('GRADED', 'Graded'), ('RESUBMIT', 'Resubmit requested')], default='SUBMITTED', max_length=10)),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_graded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_submissions', to='admissions.student')),
            ],
            options={
                'ordering': ('-submitted_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MarksEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_marks', models.DecimalField(blank=True, decimal_places=1, help_text='Internal Assessment.', max_digits=5, null=True)),
                ('ia_max', models.DecimalField(decimal_places=1, default=20, max_digits=5)),
                ('ea_marks', models.DecimalField(blank=True, decimal_places=1, help_text='External Assessment.', max_digits=5, null=True)),
                ('ea_max', models.DecimalField(decimal_places=1, default=80, max_digits=5)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='master.batch')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_published', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='master.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='admissions.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='master.subject')),
            ],
            options={
                'ordering': ('student', 'semester', 'subject'),
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['batch', 'subject'], name='academics_a_batch_i_d4334c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='academics_a_due_dat_1d72e3_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'status'], name='academics_a_student_555610_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='academics_a_assignm_22b7b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='marksentry',
            index=models.Index(fields=['batch', 'semester'], name='academics_m_batch_i_3f17ca_idx'),
        ),
        migrations.AddIndex(
            model_name='marksentry',
            index=models.Index(fields=['student', 'published'], name='academics_m_student_7f96f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marksentry',
            unique_together={('student', 'subject', 'semester')},
        ),
    ]
