# Generated by Django 5.2.13 on 2026-05-01 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_assignment_assignmentsubmission_marksentry_and_more'),
        ('admissions', '0002_initial'),
        ('master', '0006_coursesubject_subject_coursesubject_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.PositiveSmallIntegerField()),
                ('final_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_status', models.CharField(choices=[('JOB', 'Working a job'), ('ENTREPRENEUR', 'Entrepreneur'), ('HIGHER_STUDIES', 'Pursuing higher studies'), ('FAMILY_BUSINESS', 'Family business'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('workplace', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('linkedin_url', models.URLField(blank=True)),
                ('last_known_email', models.EmailField(blank=True, max_length=254)),
                ('last_known_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumni', to='master.batch')),
                ('final_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumni', to='master.program')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alumni', to='admissions.student')),
            ],
            options={
                'ordering': ('-graduation_year', 'student__student_name'),
                'indexes': [models.Index(fields=['graduation_year', 'final_program'], name='academics_a_graduat_2ee526_idx'), models.Index(fields=['current_status'], name='academics_a_current_2f30f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMPLETION', 'Course Completion'), ('PROVISIONAL', 'Provisional'), ('BONAFIDE', 'Bonafide'), ('TRANSFER', 'Transfer'), ('CHARACTER', 'Character'), ('NO_DUES', 'No Dues')], max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ISSUED', 'Issued'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='REQUESTED', max_length=10)),
                ('certificate_no', models.CharField(blank=True, db_index=True, max_length=60)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, help_text='Source enrollment for context (program / batch).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='admissions.enrollment')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_requested', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='admissions.student')),
            ],
            options={
                'ordering': ('-requested_on',),
                'indexes': [models.Index(fields=['student', 'type'], name='academics_c_student_1665f2_idx'), models.Index(fields=['status', 'type'], name='academics_c_status_6be871_idx')],
            },
        ),
    ]
