# Generated by Django 5.2.13 on 2026-05-01 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alumnirecord_certificate'),
        ('admissions', '0002_initial'),
        ('master', '0006_coursesubject_subject_coursesubject_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('duration_min', models.PositiveSmallIntegerField(help_text='How long a student has once they start.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('total_marks', models.DecimalField(decimal_places=1, default=0, help_text='Auto-recomputed from sum(question.marks).', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='master.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='master.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='master.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(help_text='Earliest the student can start.')),
                ('end_dt', models.DateTimeField(help_text='Latest the student can submit.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='NOT_STARTED', max_length=12)),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_attempts', to='admissions.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academics.test')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('MCQ', 'Multiple Choice (single correct)'), ('SHORT', 'Short Answer')], max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text='MCQ: list of strings. SHORT: ignored.')),
                ('answer_key', models.CharField(blank=True, help_text='MCQ: index of correct option (0..N-1). SHORT: optional reference answer for graders.', max_length=200)),
                ('marks', models.DecimalField(decimal_places=1, default=1, max_digits=5)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.test')),
            ],
            options={
                'ordering': ('test', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, help_text='MCQ: chosen option index as string. SHORT: free text.')),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_auto_graded', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='academics.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='academics.testquestion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_responses_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('attempt', 'question__sort_order'),
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['subject', 'status'], name='academics_t_subject_82922b_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'status'], name='academics_t_test_id_3fa266_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student', 'status'], name='academics_t_student_ec17ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('test', 'student')},
        ),
        migrations.AddIndex(
            model_name='testresponse',
            index=models.Index(fields=['attempt', 'is_auto_graded'], name='academics_t_attempt_ee3938_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testresponse',
            unique_together={('attempt', 'question')},
        ),
    ]
