# Generated by Django 5.2.13 on 2026-06-29 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_test_testattempt_testquestion_testresponse_and_more'),
        ('employees', '0004_designation_role'),
        ('master', '0010_institute_email_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=200)),
                ('assignment', models.TextField(help_text='The assignment / work described in this lesson plan.')),
                ('submission_due_date', models.DateTimeField(blank=True, null=True)),
                ('submission_due_desc', models.CharField(blank=True, max_length=200)),
                ('module_project', models.TextField(blank=True)),
                ('module_project_due', models.DateField(blank=True, null=True)),
                ('sem_end_project', models.TextField(blank=True)),
                ('sem_end_project_due', models.DateField(blank=True, null=True)),
                ('display_date', models.DateField(blank=True, help_text='When set, students only see the lesson on/after this date.', null=True)),
                ('visits_workshops', models.TextField(blank=True, help_text='Visits / workshops / seminars, if any.')),
                ('hod_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IMPROVE', 'Needs improvement')], db_index=True, default='PENDING', max_length=10)),
                ('hod_remarks', models.TextField(blank=True)),
                ('hod_decided_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IMPROVE', 'Needs improvement')], db_index=True, default='PENDING', max_length=10)),
                ('mentor_remarks', models.TextField(blank=True)),
                ('mentor_decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='master.batch')),
                ('class_mentor', models.ForeignKey(help_text='Class / batch mentor reviewer.', on_delete=django.db.models.deletion.PROTECT, related_name='lessons_as_mentor', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_created', to=settings.AUTH_USER_MODEL)),
                ('hod', models.ForeignKey(help_text='HOD / senior faculty reviewer.', on_delete=django.db.models.deletion.PROTECT, related_name='lessons_as_hod', to='employees.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['batch', 'hod_status', 'mentor_status'], name='academics_l_batch_i_520ae2_idx')],
            },
        ),
    ]
