# Generated by Django 5.2.13 on 2026-07-15 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_assignment_image'),
        ('master', '0010_institute_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='master.program'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='master.batch'),
        ),
    ]
