# Generated by Django 5.2.13 on 2026-07-21 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_backfill_assignment_program'),
        ('admissions', '0008_student_registration_number'),
        ('master', '0010_institute_email_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.TextField(blank=True, help_text='JD Annual Design Awards.')),
                ('portfolio', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_awards', to='master.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_awards_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_awards', to='admissions.student')),
            ],
            options={
                'indexes': [models.Index(fields=['batch'], name='academics_c_batch_i_51927e_idx')],
                'unique_together': {('student', 'batch')},
            },
        ),
    ]
