# Generated by Django 5.2.13 on 2026-09-01 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_closingaward'),
        ('employees', '0006_employee_employment_category'),
        ('master', '0015_elective_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='uniq_batch_date_slot_active',
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='is_elective',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_elective', False), ('status', 'SCHEDULED')), fields=('batch', 'date', 'time_slot'), name='uniq_batch_date_slot_active'),
        ),
    ]
