# Generated by Django 5.2.13 on 2026-09-28 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_elective_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='attendance_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='attendance_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='attendance_unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_schedule_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
