# Generated by Django 5.2.13 on 2026-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_attendance_unlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksentry',
            name='ea_max',
            field=models.DecimalField(decimal_places=1, default=40, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marksentry',
            name='ia_max',
            field=models.DecimalField(decimal_places=1, default=40, max_digits=5),
        ),
    ]
