# Generated by Django 5.2.13 on 2026-09-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_marks_max_default_40'),
        ('master', '0022_institute_letterhead_placement_institute_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='master.semester'),
        ),
    ]
