# Generated by Django 5.2.13 on 2026-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='occurrence_number',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='1=Primary, 2=Secondary, 3=Tertiary, 4+=Repeated.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, help_text='Last 10 digits of phone, used for dedup matching.', max_length=20),
        ),
    ]
