# Generated by Django 5.2.13 on 2026-05-01 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_alternative_email_lead_alternative_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('REGULAR', 'Regular Course'), ('SHORT', 'Short Course'), ('NEW', 'Newly launched')], help_text='One pool per program category.', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pointer', models.PositiveIntegerField(default=0, help_text='Round-robin offset; advanced after each assignment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='assign_to',
            field=models.ForeignKey(blank=True, help_text='Counsellor handling this lead. Auto-filled by round-robin when omitted; null if the pool was empty at create time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CounsellorPoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Stable order within the pool — counsellors with lower sort_order get leads first. Used for fairness when rotating.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='leads.counsellorpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pool', 'sort_order'),
                'unique_together': {('pool', 'user')},
            },
        ),
    ]
