# Generated by Django 5.2.13 on 2026-05-01 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_counsellorpool_alter_lead_assign_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='outcome_category',
            field=models.CharField(blank=True, choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold'), ('NOT_ANSWERING', 'Not Answering'), ('NOT_CONNECTED', 'Not Connected'), ('ENROLLED', 'Enrolled')], db_index=True, help_text='Required after Module F.4. Drives drip automation.', max_length=20),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='outcome_disposition',
            field=models.CharField(blank=True, help_text="Sub-disposition within the category, e.g. 'feels Fees is high'.", max_length=80),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['lead', 'outcome_category'], name='leads_leadf_lead_id_99929d_idx'),
        ),
    ]
