# Generated by Django 5.2.13 on 2026-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_application_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='lead',
            name='application_fee_mode',
            field=models.CharField(blank=True, help_text='CASH / CHEQUE / DD / ONLINE / UPI / NEFT / RTGS', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='application_fee_ref',
            field=models.CharField(blank=True, help_text='UPI txn id / cheque no / bank ref / receipt no.', max_length=120),
        ),
    ]
