# Generated by Django 5.2.13 on 2026-05-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_father_email_lead_father_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('non_responsive', 'Non Responsive'), ('application_submitted', 'Application Submitted'), ('enrolled', 'Enrolled')], db_index=True, default='active', max_length=32),
        ),
    ]
