# Generated by Django 5.2.13 on 2026-06-29 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_lead_status'),
        ('master', '0010_institute_email_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('duration_min', models.PositiveSmallIntegerField(help_text='How long a candidate has once they start.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('total_marks', models.DecimalField(decimal_places=1, default=0, help_text='Auto-recomputed from sum(question.marks).', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_exams', to='master.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_exams_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_exams', to='master.program')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EntranceExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID embedded in the public exam link.', unique=True)),
                ('start_dt', models.DateTimeField(help_text='Earliest the candidate can start.')),
                ('end_dt', models.DateTimeField(help_text='Latest the candidate can submit.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='NOT_STARTED', max_length=12)),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='leads.entranceexam')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to='leads.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EntranceExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('MCQ', 'Multiple Choice (single correct)'), ('SHORT', 'Short Answer')], max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text='MCQ: list of strings. SHORT: ignored.')),
                ('answer_key', models.CharField(blank=True, help_text='MCQ: index of correct option (0..N-1). SHORT: optional reference answer for graders.', max_length=200)),
                ('marks', models.DecimalField(decimal_places=1, default=1, max_digits=5)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='leads.entranceexam')),
            ],
            options={
                'ordering': ('exam', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EntranceExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, help_text='MCQ: chosen option index as string. SHORT: free text.')),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_auto_graded', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='leads.entranceexamattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='leads.entranceexamquestion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_responses_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('attempt', 'question__sort_order'),
            },
        ),
        migrations.AddIndex(
            model_name='entranceexam',
            index=models.Index(fields=['program', 'status'], name='leads_entra_program_ce8e67_idx'),
        ),
        migrations.AddIndex(
            model_name='entranceexamattempt',
            index=models.Index(fields=['exam', 'status'], name='leads_entra_exam_id_1d19b4_idx'),
        ),
        migrations.AddIndex(
            model_name='entranceexamattempt',
            index=models.Index(fields=['lead', 'status'], name='leads_entra_lead_id_bf17cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entranceexamattempt',
            unique_together={('exam', 'lead')},
        ),
        migrations.AddIndex(
            model_name='entranceexamresponse',
            index=models.Index(fields=['attempt', 'is_auto_graded'], name='leads_entra_attempt_830b94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entranceexamresponse',
            unique_together={('attempt', 'question')},
        ),
    ]
