# Generated by Django 5.2.13 on 2026-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_entranceexam_entranceexamattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fee_link_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
