# Generated by Django 5.2.13 on 2026-05-01 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_reporting_manager_1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelievingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('last_working_date_requested', models.DateField()),
                ('last_working_date_approved', models.DateField(blank=True, help_text='Set by HR at finalization. Used in the relieving letter.', null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved (pending HR finalize)'), ('COMPLETED', 'Completed (letters issued)'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='SUBMITTED', max_length=12)),
                ('rejected_at_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('relieving_letter_no', models.CharField(blank=True, max_length=40)),
                ('experience_letter_no', models.CharField(blank=True, max_length=40)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relieving_applications', to='employees.employee')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relieving_finalized', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relieving_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='RelievingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped (RM not configured)')], default='PENDING', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='relieving.relievingapplication')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relieving_approvals', to='employees.employee')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relieving_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('application', 'level'),
            },
        ),
        migrations.AddIndex(
            model_name='relievingapplication',
            index=models.Index(fields=['employee', 'status'], name='relieving_r_employe_95bb11_idx'),
        ),
        migrations.AddConstraint(
            model_name='relievingapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'IN_REVIEW', 'APPROVED'])), fields=('employee',), name='uniq_open_relieving_per_employee'),
        ),
        migrations.AddIndex(
            model_name='relievingapproval',
            index=models.Index(fields=['approver', 'status'], name='relieving_r_approve_003154_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relievingapproval',
            unique_together={('application', 'level')},
        ),
    ]
