# Generated by Django 5.2.13 on 2026-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relieving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relievingapplication',
            name='experience_letter_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
