# Generated by Django 5.2.13 on 2026-08-27 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0011_lead_fee_link_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Our id for the order, as the bank knows it. SmartGateway caps this at 20 chars, alphanumeric only.', max_length=21, unique=True)),
                ('sg_order_ref', models.CharField(blank=True, db_index=True, help_text="SmartGateway's own 'ordeh_xxx' id from the session response.", max_length=64)),
                ('payment_page_url', models.URLField(blank=True, help_text='payment_links.web — the hosted page we redirect to.', max_length=500)),
                ('session_expires_at', models.DateTimeField(blank=True, help_text='When payment_page_url stops working. A fresh order is minted when a student returns after this.', null=True)),
                ('status', models.CharField(choices=[('NEW', 'Created, not yet attempted'), ('STARTED', 'Started'), ('PENDING_VBV', 'Authentication in progress'), ('AUTHORIZING', 'Awaiting bank response'), ('CAPTURE_INITIATED', 'Capture in progress'), ('VOID_INITIATED', 'Void in progress'), ('CHARGED', 'Charged (paid)'), ('AUTHORIZED', 'Authorized, awaiting capture'), ('AUTHENTICATION_FAILED', 'Authentication failed'), ('AUTHORIZATION_FAILED', 'Authorization failed'), ('JUSPAY_DECLINED', 'Declined by gateway'), ('CAPTURE_FAILED', 'Capture failed'), ('VOID_FAILED', 'Void failed'), ('VOIDED', 'Voided'), ('AUTO_REFUNDED', 'Auto-refunded')], db_index=True, default='NEW', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('txn_id', models.CharField(blank=True, max_length=80)),
                ('txn_uuid', models.CharField(blank=True, max_length=64)),
                ('payment_method', models.CharField(blank=True, help_text='VISA / MASTERCARD / UPI …', max_length=40)),
                ('payment_method_type', models.CharField(blank=True, help_text='CARD / NB / WALLET / UPI …', max_length=24)),
                ('bank_error_code', models.CharField(blank=True, max_length=64)),
                ('bank_error_message', models.CharField(blank=True, max_length=300)),
                ('charged_at', models.DateTimeField(blank=True, null=True)),
                ('last_payload', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Embedded in the public pay URL. Never reused.', unique=True)),
                ('purpose', models.CharField(choices=[('APPLICATION_FEE', 'Application fee (lead)')], db_index=True, default='APPLICATION_FEE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rupees. SmartGateway takes this as a 2dp string.', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, help_text='Set for APPLICATION_FEE requests.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='leads.lead')),
                ('paid_order', models.ForeignKey(blank=True, help_text='The order that actually settled this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.paymentorder')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.paymentrequest'),
        ),
        migrations.CreateModel(
            name='SmartGatewayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text="The payload's `id`, e.g. 'evt_V2_xxx' — our idempotency key.", max_length=120, unique=True)),
                ('event_name', models.CharField(db_index=True, max_length=60)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('SKIPPED', "Skipped (event we don't act on)"), ('ERROR', 'Error')], default='RECEIVED', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.paymentorder')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['lead', 'status'], name='payments_pa_lead_id_6c0030_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['purpose', 'status'], name='payments_pa_purpose_210b80_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['request', 'status'], name='payments_pa_request_90b078_idx'),
        ),
    ]
