# Generated by Django 5.2.13 on 2026-08-31 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_installment_kind'),
        ('leads', '0011_lead_fee_link_sent_at'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='installment',
            field=models.ForeignKey(blank=True, help_text='Set for FEE_INSTALLMENT requests — the scheduled row the student is paying from the portal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='fees.installment'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='purpose',
            field=models.CharField(choices=[('APPLICATION_FEE', 'Application fee (lead)'), ('FEE_INSTALLMENT', 'Fee installment (student)')], db_index=True, default='APPLICATION_FEE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['installment', 'status'], name='payments_pa_install_94b22f_idx'),
        ),
    ]
