# Generated by Django 5.2.13 on 2026-09-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentrequest_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='account',
            field=models.CharField(blank=True, db_index=True, help_text='Settlement account key from payments.routing.ACCOUNTS (JDSD_TRUST / JDIFT_MAIN / JDIFT_ROYALTY). Blank = the single shared merchant used before routing existed.', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='gateway',
            field=models.CharField(db_index=True, default='smartgateway', max_length=20),
        ),
    ]
