# Generated by Django 5.2.13 on 2026-09-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentrequest_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_page_url',
            field=models.URLField(blank=True, help_text="The hosted page we redirect to — SmartGateway's payment_links.web or a Razorpay link's short_url.", max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='sg_order_ref',
            field=models.CharField(blank=True, db_index=True, help_text="The gateway's own id: SmartGateway's 'ordeh_xxx' from the session response, or Razorpay's 'plink_xxx'.", max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'Created, not yet attempted'), ('STARTED', 'Started'), ('PENDING_VBV', 'Authentication in progress'), ('AUTHORIZING', 'Awaiting bank response'), ('CAPTURE_INITIATED', 'Capture in progress'), ('VOID_INITIATED', 'Void in progress'), ('CHARGED', 'Charged (paid)'), ('AUTHORIZED', 'Authorized, awaiting capture'), ('AUTHENTICATION_FAILED', 'Authentication failed'), ('AUTHORIZATION_FAILED', 'Authorization failed'), ('JUSPAY_DECLINED', 'Declined by gateway'), ('CAPTURE_FAILED', 'Capture failed'), ('VOID_FAILED', 'Void failed'), ('VOIDED', 'Voided'), ('AUTO_REFUNDED', 'Auto-refunded'), ('EXPIRED', 'Link expired unpaid'), ('CANCELLED', 'Link cancelled')], db_index=True, default='NEW', max_length=24),
        ),
    ]
