# Generated by Django 5.2.13 on 2026-05-01 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_initial'),
        ('employees', '0002_alter_employee_reporting_manager_1'),
        ('master', '0006_coursesubject_subject_coursesubject_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_date', models.DateField(db_index=True)),
                ('slot1', models.TextField(blank=True, help_text='Activities in the 9:30-12:30 slot.')),
                ('slot2', models.TextField(blank=True, help_text='Activities in the 1:30-5:30 slot.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-rep_date', 'user'),
                'unique_together': {('rep_date', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BatchMentorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('avg_attendance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_marks_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('behavioural_notes', models.TextField(blank=True)),
                ('academic_concerns', models.TextField(blank=True)),
                ('dropout_risks', models.TextField(blank=True)),
                ('initiatives', models.TextField(blank=True)),
                ('additional_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor_reports', to='master.batch')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_mentor_reports', to='employees.employee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_mentor_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-month'),
                'unique_together': {('batch', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_description', models.CharField(blank=True, help_text='Free-text target if no FK fits.', max_length=200)),
                ('category', models.CharField(choices=[('TIMETABLE', 'Timetable / class compliance'), ('ATTENDANCE', 'Attendance / freeze compliance'), ('REPORTING', 'Daily report not submitted'), ('FEEDBACK', 'Negative feedback trend'), ('ACADEMIC', 'Academic outcome concern'), ('OTHER', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_resolved', to=settings.AUTH_USER_MODEL)),
                ('target_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_flags', to='master.batch')),
                ('target_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_flags', to='employees.employee')),
                ('target_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_flags', to='admissions.student')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['resolved_at'], name='audit_repor_resolve_920bb7_idx'), models.Index(fields=['category', 'severity'], name='audit_repor_categor_75a5a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseEndReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField()),
                ('summary', models.TextField()),
                ('learning_outcomes', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('avg_attendance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_marks_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hod_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned for revision')], default='PENDING', max_length=10)),
                ('hod_remarks', models.TextField(blank=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_end_reports', to='master.batch')),
                ('hod_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_end_reviews', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_end_reports', to='employees.employee')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_end_reports', to='master.subject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_end_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-completed_on',),
                'unique_together': {('instructor', 'subject', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='FacultyDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('hours_taught', models.DecimalField(decimal_places=1, default=0, help_text='Self-reported teaching hours.', max_digits=4)),
                ('non_academic_hours', models.DecimalField(decimal_places=1, default=0, help_text='Committee work, mentoring, admin tasks etc.', max_digits=4)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='employees.employee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', 'faculty'),
                'indexes': [models.Index(fields=['faculty', 'date'], name='audit_repor_faculty_e41dfe_idx')],
                'unique_together': {('faculty', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FacultySelfAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1 (Apr-Jun)'), (2, 'Q2 (Jul-Sep)'), (3, 'Q3 (Oct-Dec)'), (4, 'Q4 (Jan-Mar)')])),
                ('achievements', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('plans', models.TextField(blank=True)),
                ('green_flags', models.TextField(blank=True, help_text='Notable positives — mentorship, initiatives, results.')),
                ('red_flags', models.TextField(blank=True, help_text='Areas needing improvement.')),
                ('auditor_remarks', models.TextField(blank=True)),
                ('auditor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_appraisals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self_appraisals', to='employees.employee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_appraisals_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-quarter'),
                'unique_together': {('faculty', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MIDWAY', 'Mid-course'), ('END', 'End-of-course')], max_length=10)),
                ('rating_overall', models.PositiveSmallIntegerField(help_text='1 (poor) to 5 (excellent)')),
                ('rating_clarity', models.PositiveSmallIntegerField(default=0)),
                ('rating_engagement', models.PositiveSmallIntegerField(default=0)),
                ('rating_responsiveness', models.PositiveSmallIntegerField(default=0)),
                ('what_worked', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='master.batch')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_received', to='employees.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_given', to='admissions.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_received', to='master.subject')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['instructor', 'type'], name='audit_repor_instruc_0143eb_idx'), models.Index(fields=['subject', 'batch', 'type'], name='audit_repor_subject_443f1a_idx')],
                'unique_together': {('student', 'subject', 'instructor', 'batch', 'type')},
            },
        ),
    ]
