# Generated by Django 5.2.13 on 2026-06-29 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_forms_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text box'), ('TEXTAREA', 'Long text'), ('RADIO', 'Radio (single choice)'), ('DROPDOWN', 'Dropdown (single select)'), ('MULTISELECT', 'Multi-select'), ('CHECKBOX', 'Checkboxes (multi choice)'), ('RATING', 'Star rating'), ('DATE', 'Date'), ('TIME', 'Time'), ('DATETIME', 'Date & time')], max_length=12)),
                ('options', models.JSONField(blank=True, default=list, help_text='Choice types: list of option strings. Others: ignored.')),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Type-specific config, e.g. {"max_rating": 5}.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='audit_reports.auditform')),
            ],
            options={
                'ordering': ('form', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AuditSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='audit_reports.auditform')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='audit_reports.auditformfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='audit_reports.auditsubmission')),
            ],
            options={
                'ordering': ('submission', 'field__sort_order', 'field_id'),
            },
        ),
        migrations.AddIndex(
            model_name='auditform',
            index=models.Index(fields=['status'], name='audit_repor_status_ad7eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsubmission',
            index=models.Index(fields=['form', 'created_at'], name='audit_repor_form_id_9edb0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditanswer',
            unique_together={('submission', 'field')},
        ),
    ]
