# Generated by Django 5.2.13 on 2026-06-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_reports', '0002_auditform_auditformfield_auditsubmission_auditanswer_and_more'),
        ('roles', '0002_granular_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditform',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Only users holding one of these roles can see and fill the form.', related_name='audit_forms', to='roles.role'),
        ),
    ]
