# Generated by Django 5.2.13 on 2026-06-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_reports', '0003_auditform_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultydailyreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facultydailyreport',
            name='hours_taught',
        ),
        migrations.RemoveField(
            model_name='facultydailyreport',
            name='remarks',
        ),
        migrations.AddField(
            model_name='facultydailyreport',
            name='academic_description',
            field=models.TextField(blank=True, help_text='Academic documentation — classes, prep, etc.'),
        ),
        migrations.AddField(
            model_name='facultydailyreport',
            name='academic_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='facultydailyreport',
            name='non_academic_description',
            field=models.TextField(blank=True, help_text='Committee work, mentoring, admin tasks etc.'),
        ),
        migrations.AddField(
            model_name='facultydailyreport',
            name='others_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facultydailyreport',
            name='others_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='facultydailyreport',
            name='non_academic_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
