# Generated by Django 5.2.13 on 2026-07-03 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_reports', '0004_remove_facultydailyreport_description_and_more'),
        ('employees', '0004_designation_role'),
        ('master', '0010_institute_email_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroHourReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, help_text='Date the 0-Hour session was conducted.')),
                ('batch_strength', models.PositiveIntegerField()),
                ('zero_hour_attendance', models.PositiveIntegerField(help_text='Students present for the 0-Hour session.')),
                ('avg_attendance_first_half', models.DecimalField(blank=True, decimal_places=2, help_text='Average batch attendance, 1st–15th of the month (%).', max_digits=5, null=True)),
                ('avg_attendance_month_end', models.DecimalField(blank=True, decimal_places=2, help_text='Average batch attendance at month end (%).', max_digits=5, null=True)),
                ('agenda', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('months_to_exams', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exam_preparations', models.TextField(blank=True)),
                ('exam_preparation_details', models.TextField(blank=True, help_text='Schedule / arrangements to achieve the above.')),
                ('months_to_portfolios', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('months_to_internships', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('internship_preparations', models.TextField(blank=True, help_text="Preparations for the batch to be 'Internship ready'.")),
                ('months_to_passout', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, help_text='Activities planned / completed for the batch.')),
                ('remarks', models.TextField(blank=True)),
                ('hod_discussion', models.TextField(blank=True, help_text='Batch issues discussed with HOD / Principal + outcomes.')),
                ('action_taken', models.TextField(blank=True, help_text='Action taken on the issues addressed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zero_hour_reports', to='master.batch')),
                ('mentor', models.ForeignKey(help_text='Class mentor.', on_delete=django.db.models.deletion.PROTECT, related_name='zero_hour_reports', to='employees.employee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zero_hour_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-report_date', '-created_at'),
                'indexes': [models.Index(fields=['report_date'], name='audit_repor_report__53380d_idx'), models.Index(fields=['batch', 'report_date'], name='audit_repor_batch_i_2fc8d9_idx')],
            },
        ),
    ]
