# Generated by Django 5.2.13 on 2026-07-10 12:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_student_registration_number'),
        ('audit_reports', '0006_drop_zerohour_exam_internship_fields'),
        ('employees', '0004_designation_role'),
        ('master', '0010_institute_email_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceflag',
            name='kind',
            field=models.CharField(choices=[('FLAG', 'Flag'), ('STAR', 'Star')], db_index=True, default='FLAG', max_length=5),
        ),
        migrations.AddField(
            model_name='complianceflag',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Star rating 1–5. Set only when kind=STAR.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='complianceflag',
            name='category',
            field=models.CharField(choices=[('TIMETABLE', 'Timetable / class compliance'), ('ATTENDANCE', 'Attendance / freeze compliance'), ('REPORTING', 'Daily report not submitted'), ('FEEDBACK', 'Negative feedback trend'), ('ACADEMIC', 'Academic outcome concern'), ('OTHER', 'Other'), ('PERFORMANCE', 'Outstanding performance'), ('TIMELINESS', 'Timely completion of tasks'), ('STUDENT_FEEDBACK', 'Excellent student feedback'), ('INNOVATION', 'Innovation'), ('ACHIEVEMENT_OTHER', 'Other achievement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complianceflag',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Applies to flags. Ignored for stars.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='complianceflag',
            index=models.Index(fields=['kind', 'resolved_at'], name='audit_repor_kind_69b88d_idx'),
        ),
    ]
