# Generated by Django 5.2.13 on 2026-04-29 17:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text='1-indexed installment number for this enrollment.')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='admissions.enrollment')),
            ],
            options={
                'ordering': ('enrollment', 'sequence'),
                'unique_together': {('enrollment', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('approver_remarks', models.TextField(blank=True)),
                ('decided_on', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions_decided', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='admissions.enrollment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_on',),
                'indexes': [models.Index(fields=['enrollment', 'status'], name='fees_conces_enrollm_8aeb5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=40, unique=True)),
                ('basic_fee', models.DecimalField(decimal_places=2, help_text='Pre-tax amount.', max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total received (basic_fee + sgst + cgst + igst).', max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('DD', 'Demand Draft'), ('ONLINE', 'Online (card / netbanking)'), ('UPI', 'UPI'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], max_length=10)),
                ('instrument_ref', models.CharField(blank=True, help_text='Cheque / DD number, bank txn id, UPI ref.', max_length=80)),
                ('bank', models.CharField(blank=True, max_length=120)),
                ('received_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('cancelled_on', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_cancelled', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='admissions.enrollment')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_received', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, help_text='Optional — receipts can be linked to a specific installment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='fees.installment')),
            ],
            options={
                'ordering': ('-received_date', '-created_on'),
                'indexes': [models.Index(fields=['enrollment', 'status'], name='fees_feerec_enrollm_66a3f2_idx'), models.Index(fields=['receipt_no'], name='fees_feerec_receipt_25e3db_idx'), models.Index(fields=['received_date'], name='fees_feerec_receive_06ee4b_idx')],
            },
        ),
    ]
