# Generated by Django 5.2.13 on 2026-07-14 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_student_registration_number'),
        ('fees', '0003_drop_qfixwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Description of the fee.', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_fees_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_fees', to='admissions.enrollment')),
            ],
            options={
                'ordering': ('enrollment', 'id'),
            },
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='other_fee',
            field=models.ForeignKey(blank=True, help_text='Set when this receipt pays an ad-hoc Other fee. Such receipts are excluded from the course-fee balance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='fees.otherfee'),
        ),
        migrations.AddIndex(
            model_name='otherfee',
            index=models.Index(fields=['enrollment'], name='fees_otherf_enrollm_3a43fc_idx'),
        ),
    ]
