# Generated by Django 5.2.13 on 2026-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_otherfee_feereceipt_other_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='kind',
            field=models.CharField(choices=[('COURSE', 'Course fee'), ('REGISTRATION', 'Registration fee')], db_index=True, default='COURSE', help_text='REGISTRATION rows carry the mandatory yearly registration charge (FeeTemplate.registration_fee). They are carved out of the same total_fee as COURSE rows — never added on top — and are locked: the amount cannot be edited, the row cannot be deleted, and at most one exists per (student, academic year).', max_length=12),
        ),
    ]
