# Generated by Django 5.2.13 on 2026-05-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0003_student_parent_user_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_edate', models.DateField()),
                ('student_remarks', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=10)),
                ('batch_mentor_email', models.EmailField(max_length=254)),
                ('module_mentor_email', models.EmailField(blank=True, max_length=254)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('approver_remarks', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leaves_decided', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='admissions.student')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['student', 'status'], name='student_lea_student_cd12ac_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('leave_edate__gte', models.F('leave_date'))), name='student_leave_dates_ordered')],
            },
        ),
    ]
