# Generated by Django 5.2.13 on 2026-04-29 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Promoted'), (4, 'Dropped'), (5, 'Alumni')], default=1)),
                ('elective_subjects', models.TextField(blank=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_form_id', models.CharField(blank=True, help_text='Auto-generated as {INSTITUTE}-{YYYY}-{seq} on first save.', max_length=30, unique=True)),
                ('student_name', models.CharField(max_length=160)),
                ('father_name', models.CharField(blank=True, max_length=160)),
                ('mother_name', models.CharField(blank=True, max_length=160)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('OTHER', 'Other')], default='GEN', max_length=10)),
                ('study_medium', models.CharField(choices=[('E', 'English'), ('H', 'Hindi'), ('O', 'Other')], default='E', max_length=1)),
                ('nationality', models.CharField(choices=[('INDIAN', 'Indian'), ('OTHERS', 'Others')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('current_address', models.TextField(blank=True)),
                ('current_pincode', models.CharField(blank=True, max_length=10)),
                ('permanent_address', models.TextField(blank=True)),
                ('permanent_pincode', models.CharField(blank=True, max_length=10)),
                ('student_mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be in international format (e.g. +919900112233).', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('father_mobile', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be in international format (e.g. +919900112233).', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('mother_mobile', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be in international format (e.g. +919900112233).', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('student_email', models.EmailField(max_length=254)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('institute_email', models.EmailField(blank=True, help_text='Optional institute-issued email.', max_length=254)),
                ('father_occupation', models.CharField(blank=True, max_length=120)),
                ('mother_occupation', models.CharField(blank=True, max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(choices=[('SSLC', '10th / SSLC'), ('PUC', '12th / PUC / Equivalent'), ('DIPLOMA', 'Diploma'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('AADHAAR', 'Aadhaar'), ('PASSPORT', 'Passport'), ('PAN', 'PAN'), ('PHOTO', 'Passport-size Photo'), ('OTHER', 'Other')], max_length=20)),
                ('regno_yearpassing', models.CharField(blank=True, max_length=80)),
                ('school_college', models.CharField(blank=True, max_length=200)),
                ('university_board', models.CharField(blank=True, max_length=200)),
                ('certificate_no', models.CharField(blank=True, max_length=80)),
                ('percent_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='students/docs/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-uploaded_on',),
            },
        ),
    ]
