# Generated by Django 5.2.13 on 2026-05-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_user_account',
            field=models.OneToOneField(blank=True, help_text='User account used by the parent to log into the parent panel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_of_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
