# Generated by Django 5.2.13 on 2026-05-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_student_parent_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
