# Generated by Django 5.2.13 on 2026-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_studentremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='portal_temp_password',
            field=models.CharField(blank=True, help_text='Last issued plaintext password for the student portal. Stored so staff can re-share it without forcing a reset. Mirrors the JD_ERP PHP behavior — treat as sensitive.', max_length=64),
        ),
        migrations.AlterField(
            model_name='studentremark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
