# Generated by Django 5.2.13 on 2026-05-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_student_portal_temp_password_alter_studentremark_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, help_text='Institute-assigned registration / enrolment number. Filled manually by HR and shown on the student profile.', max_length=50),
        ),
    ]
