# Generated by Django 5.2.13 on 2026-09-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='declaration_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the student affirmed the declaration.', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rules_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the student accepted the rules & regulations.', null=True),
        ),
    ]
