# Generated by Django 5.2.13 on 2026-09-07 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_student_declaration_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_number',
            field=models.CharField(blank=True, db_index=True, help_text='12-digit UIDAI number, stored unformatted.', max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar must be 12 digits and cannot start with 0 or 1.', regex='^[2-9]\\d{11}$')]),
        ),
    ]
