# Generated by Django 5.2.13 on 2026-09-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_dropout_permissions'),
        ('master', '0022_institute_letterhead_placement_institute_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_transfers_made', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='admissions.enrollment')),
                ('from_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.academicyear')),
                ('from_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.batch')),
                ('from_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.campus')),
                ('from_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.program')),
                ('from_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_transfers', to='admissions.student')),
                ('to_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.academicyear')),
                ('to_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.batch')),
                ('to_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.campus')),
                ('to_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.program')),
                ('to_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.semester')),
            ],
            options={
                'ordering': ('-created_on', '-id'),
            },
        ),
    ]
