# Generated by Django 5.2.13 on 2026-04-28 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_institute_state_campus_institute_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='emp_code must be uppercase letters, digits, and dashes only.', regex='^[A-Z0-9-]+$')])),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('family_name', models.CharField(blank=True, max_length=60)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(choices=[('INDIAN', 'Indian'), ('OTHERS', 'Others')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('qualification', models.CharField(blank=True, max_length=120)),
                ('employment_type', models.PositiveSmallIntegerField(choices=[(1, 'Full-time'), (2, 'Part-time')])),
                ('date_of_appointment', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('mobile_primary', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be in international format, e.g. +919900112233.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('mobile_alternate', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be in international format, e.g. +919900112233.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('email_primary', models.EmailField(max_length=254, unique=True)),
                ('email_alternate', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='employees/qr/')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='master.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('current_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_employees', to='master.city')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_employees', to='master.state')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.designation')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='master.institute')),
                ('permanent_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_employees', to='master.city')),
                ('permanent_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_employees', to='master.state')),
                ('reporting_manager_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports_l1', to='employees.employee')),
                ('reporting_manager_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports_l2', to='employees.employee')),
                ('reporting_manager_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports_l3', to='employees.employee')),
                ('reporting_manager_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports_l4', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_updated', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'indexes': [models.Index(fields=['emp_code'], name='employees_e_emp_cod_2bf689_idx'), models.Index(fields=['email_primary'], name='employees_e_email_p_42bdd2_idx'), models.Index(fields=['campus', 'status'], name='employees_e_campus__ca9308_idx'), models.Index(fields=['department', 'status'], name='employees_e_departm_5a5710_idx')],
            },
        ),
    ]
