# Generated by Django 5.2.13 on 2026-04-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reporting_manager_1',
            field=models.ForeignKey(blank=True, help_text='Required by HR policy for all employees except the top-level director (who has nobody to report to). API serializer enforces non-null for normal creates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports_l1', to='employees.employee'),
        ),
    ]
