# Generated by Django 5.2.13 on 2026-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_reporting_manager_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='portal_temp_password',
            field=models.CharField(blank=True, help_text="Last issued plaintext password for the employee's portal account. Stored so HR can re-share it without forcing a reset. Mirrors the JD_ERP PHP behavior — treat as sensitive.", max_length=64),
        ),
    ]
