# Generated by Django 5.2.13 on 2026-05-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_portal_temp_password'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='role',
            field=models.ForeignKey(blank=True, help_text='When set, the portal user for any employee with this designation receives this role on provisioning.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='roles.role'),
        ),
    ]
