# Generated by Django 5.2.13 on 2026-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_category',
            field=models.CharField(blank=True, choices=[('CONTRACT', 'Contract'), ('PROFESSIONAL', 'Professional')], max_length=20),
        ),
    ]
