# Generated by Django 5.2.13 on 2026-09-16 14:54

"""Stop storing the employee portal password in plain text. The audit
log copies are scrubbed by admissions 0011, which runs first."""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_employment_category'),
        ('admissions', '0011_drop_portal_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='portal_temp_password',
        ),
    ]
