# Generated by Django 5.2.13 on 2026-07-14 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_student_registration_number'),
        ('appointments', '0001_initial'),
        ('employees', '0004_designation_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentappointment',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_appointments', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='studentappointment',
            name='team',
            field=models.CharField(blank=True, choices=[('MANAGEMENT', 'Management'), ('ADMISSIONS', 'Admissions'), ('ACCOUNTS', 'Accounts / Fees'), ('ACADEMICS', 'Academics'), ('EXAMINATION', 'Examination'), ('PLACEMENT', 'Placement'), ('OTHER', 'Other')], max_length=12),
        ),
        migrations.AddIndex(
            model_name='studentappointment',
            index=models.Index(fields=['faculty', 'status'], name='appointment_faculty_b0b275_idx'),
        ),
    ]
