# Generated by Django 5.2.13 on 2026-04-29 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_academicyear_degree_semester_batch_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time non-refundable fee at application time.', max_digits=10)),
                ('course_fee', models.DecimalField(decimal_places=2, default=0, help_text='Tuition / course fee for the period.', max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, help_text='Misc fees (uniform, transport, etc.).', max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, help_text='The sum payable. Stored explicitly (not computed) so admins can override after concessions/discounts.', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='master.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='master.campus')),
                ('course', models.ForeignKey(blank=True, help_text='Optional — leave blank if the same fee covers the whole program.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='master.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='master.program')),
            ],
            options={
                'ordering': ('-academic_year__start_date', 'campus', 'program'),
                'indexes': [models.Index(fields=['academic_year', 'campus', 'program'], name='master_feet_academi_c0b505_idx')],
            },
        ),
    ]
