# Generated by Django 5.2.13 on 2026-05-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_feetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('REGULAR', 'Regular Course (1-4 yrs)'), ('SHORT', 'Short Course (3-11 mo)'), ('NEW', 'Newly launched')], db_index=True, default='REGULAR', help_text='Drives which counsellor pool a lead is routed to.', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='certification',
            field=models.CharField(blank=True, help_text='e.g. BESTIU, BCU, JD.', max_length=20),
        ),
    ]
