# Generated by Django 5.2.13 on 2026-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_coursesubject_subject_coursesubject_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='feedback_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='feedback_link_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
