# Generated by Django 5.2.13 on 2026-05-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_remove_enrollment_course_remove_student_course'),
        ('master', '0007_batch_feedback_link_batch_feedback_link_enabled'),
    ]

    operations = [
        # Drop the through model first — its unique_together references the
        # FKs we're about to drop, so clear it before touching anything else
        # (SQLite recreates the table on field removal).
        migrations.AlterUniqueTogether(
            name='coursesubject',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='CourseSubject',
        ),
        # Subject's M2M is just metadata now (the through model is gone).
        migrations.RemoveField(
            model_name='subject',
            name='courses',
        ),
        # Other FKs into Course.
        migrations.RemoveField(
            model_name='feetemplate',
            name='course',
        ),
        # Finally drop the model itself.
        migrations.DeleteModel(
            name='Course',
        ),
    ]
