# Generated by Django 5.2.13 on 2026-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_restore_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='email_domain',
            field=models.CharField(blank=True, help_text='Domain used for personalised student portal emails — e.g. `jdift.in`. When blank, falls back to `<code>.in` lowercased.', max_length=120),
        ),
    ]
