# Generated by Django 5.2.13 on 2026-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_institute_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='image',
            field=models.ImageField(blank=True, help_text='Shown on the dashboard campus cards (PHP `campus_img`).', null=True, upload_to='campus/images/'),
        ),
    ]
