# Generated by Django 5.2.13 on 2026-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_feetemplate_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('REGULAR', 'Regular Course (1-4 yrs)'), ('SHORT', 'Short Course (3-11 mo)'), ('NEW', 'Newly launched')], db_index=True, default='REGULAR', help_text='Reporting / grouping only. Lead assignment rotates over all counsellors regardless of category.', max_length=10),
        ),
    ]
