# Generated by Django 5.2.13 on 2026-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_program_institute_degree_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Legacy `subject_master.iselective`. Elective subjects may share one timetable slot with other electives, and their attendance roster is limited to the students who chose them (Enrollment.elective_subjects).'),
        ),
    ]
