# Generated by Django 5.2.13 on 2026-09-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_elective_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',), 'verbose_name': 'Program year', 'verbose_name_plural': 'Program years'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.ManyToManyField(blank=True, help_text='Semesters this year covers — the normalised form of legacy `course_master.sem_id`, which held them as a comma-separated list queried with FIND_IN_SET.', related_name='courses', to='master.semester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Year label, e.g. "Year 1" (legacy `course_name`).', max_length=160),
        ),
    ]
