# Generated by Django 5.2.13 on 2026-09-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_program_year_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Legacy `subject_master.program_id`. Nullable only for rows created before this field existed — set it on every new subject.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='master.program'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Legacy `subject_master.sem_id`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='master.semester'),
        ),
    ]
