# Generated by Django 5.2.13 on 2026-09-04 13:06

import django.db.models.deletion
from django.db import migrations, models

#: The degree-awarding bodies, seeded so the field is usable at once.
UNIVERSITIES = [
    ("MSBCU", "Manmohan Singh Bengaluru City University"),
    ("BESTIU", "Bharatiya Engineering Science and Technology Innovation "
               "University"),
    ("GOA", "Goa University"),
]

#: How the legacy free-text `Program.certification` maps onto them.
#: "JD" is deliberately absent — it is the institutes' own certification,
#: not a university, so those programs keep a null university.
CERTIFICATION_TO_CODE = {
    "BCU": "MSBCU",
    "BESTIU": "BESTIU",
    "GOA": "GOA",
}


def seed_and_backfill(apps, schema_editor):
    University = apps.get_model("master", "University")
    Program = apps.get_model("master", "Program")

    by_code = {}
    for code, name in UNIVERSITIES:
        uni, _ = University.objects.get_or_create(
            code=code, defaults={"name": name},
        )
        by_code[code] = uni

    matched, jd, unmapped = 0, 0, {}
    for program in Program.objects.exclude(certification=""):
        cert = (program.certification or "").strip().upper()
        code = CERTIFICATION_TO_CODE.get(cert)
        if code:
            program.university = by_code[code]
            program.save(update_fields=["university"])
            matched += 1
        elif cert == "JD":
            jd += 1
        else:
            unmapped[cert] = unmapped.get(cert, 0) + 1

    print(f"\n  master.0018: seeded {len(by_code)} universities.")
    print(f"  master.0018: linked {matched} program(s) to a university.")
    print(f"  master.0018: left {jd} JD-certified program(s) with none "
          f"(JD confers no degree).")
    if unmapped:
        print(f"  master.0018: unrecognised certification codes, left "
              f"null: {unmapped}")


def unlink(apps, schema_editor):
    """Reverse: drop the links. The seeded rows go with the table."""
    apps.get_model("master", "Program").objects.update(university=None)


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_subject_program_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short code as used on programs, e.g. MSBCU, BESTIU.', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='certification',
            field=models.CharField(blank=True, help_text='Legacy free-text affiliation code (BESTIU, BCU, JD). Superseded by `university`; kept because existing rows and reports still read it.', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Degree-awarding body. Null for JD-certified programs, which no university confers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='master.university'),
        ),
        migrations.RunPython(seed_and_backfill, unlink),
    ]
