# Generated by Django 5.2.13 on 2026-09-04 13:11

import django.db.models.deletion
from django.db import migrations, models


def clone_semesters_per_program(apps, schema_editor):
    """Give every program its own copy of each shared semester.

    Semesters were global, so one "Semester 1" row was shared by all 60
    programs. Each program now needs its own, and every row that pointed
    at the shared semester must be repointed at its program's copy.

    Consumers all know their program, directly or one hop away:
      Subject.program, Course.program, CurriculumMapping.program,
      Enrollment.program, MarksEntry.batch.program
    """
    Semester = apps.get_model("master", "Semester")
    Program = apps.get_model("master", "Program")
    Subject = apps.get_model("master", "Subject")
    Course = apps.get_model("master", "Course")
    Curriculum = apps.get_model("master", "CurriculumMapping")
    Enrollment = apps.get_model("admissions", "Enrollment")
    MarksEntry = apps.get_model("academics", "MarksEntry")

    originals = list(Semester.objects.filter(program__isnull=True))
    if not originals:
        return

    programs = list(Program.objects.all())
    if not programs:
        # Nothing to attach them to; leave the rows as they are rather
        # than deleting data.
        print("\n  master.0019: no programs, left semesters unowned.")
        return

    # (program_id, original_semester_id) -> cloned semester id
    clones = {}
    for program in programs:
        for original in originals:
            clone = Semester.objects.create(
                program=program,
                name=original.name,
                number=original.number,
                is_active=original.is_active,
            )
            clones[(program.id, original.id)] = clone.id

    def repoint(queryset, program_getter, field="semester"):
        moved = 0
        for row in queryset:
            old_id = getattr(row, f"{field}_id")
            if old_id is None:
                continue
            program_id = program_getter(row)
            new_id = clones.get((program_id, old_id))
            if new_id is None:
                continue
            setattr(row, f"{field}_id", new_id)
            row.save(update_fields=[field])
            moved += 1
        return moved

    counts = {
        "subjects": repoint(
            Subject.objects.filter(semester__isnull=False),
            lambda r: r.program_id,
        ),
        "curriculum": repoint(
            Curriculum.objects.all(), lambda r: r.program_id,
        ),
        "enrollments": repoint(
            Enrollment.objects.all(), lambda r: r.program_id,
        ),
        "marks": repoint(
            MarksEntry.objects.select_related("batch").all(),
            lambda r: r.batch.program_id,
        ),
    }

    # Course.semesters is a many-to-many, so swap membership per row.
    course_links = 0
    for course in Course.objects.prefetch_related("semesters"):
        current = list(course.semesters.all())
        if not current:
            continue
        replacement = [
            clones[(course.program_id, sem.id)]
            for sem in current
            if (course.program_id, sem.id) in clones
        ]
        if replacement:
            course.semesters.set(replacement)
            course_links += len(replacement)
    counts["program_year_links"] = course_links

    # The shared originals are now unreferenced.
    Semester.objects.filter(
        pk__in=[o.id for o in originals], program__isnull=True,
    ).delete()

    print(
        f"\n  master.0019: cloned {len(originals)} semester(s) across "
        f"{len(programs)} program(s) -> {len(clones)} rows."
    )
    print(f"  master.0019: repointed {counts}.")


def unclone(apps, schema_editor):
    """Reverse: collapse back to one shared set, keeping the lowest id
    per number. Lossy, like any un-normalisation."""
    Semester = apps.get_model("master", "Semester")
    seen = {}
    for sem in Semester.objects.order_by("number", "pk"):
        if sem.number not in seen:
            sem.program = None
            sem.save(update_fields=["program"])
            seen[sem.number] = sem.pk
    Semester.objects.filter(program__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_university'),
        # The clone step repoints rows in these apps, so their historical
        # models must already exist.
        ('admissions', '0009_student_declaration_accepted_at_and_more'),
        ('academics', '0011_elective_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('program', 'number')},
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Owning program. Nullable only for rows that predate this field — set it on every new semester.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='master.program'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(help_text='e.g. Semester 1', max_length=40),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.RunPython(clone_semesters_per_program, unclone),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('program', 'number'), name='uniq_semester_program_number'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('program', 'name'), name='uniq_semester_program_name'),
        ),
    ]
