# Generated by Django 5.2.13 on 2026-09-04 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_semester_per_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='start_semester',
            field=models.ForeignKey(blank=True, help_text="Semester this cohort ENTERS at. Informational only — a batch persists across semesters, and a student's current semester lives on their Enrollment, which is what promotion advances.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches_starting', to='master.semester'),
        ),
    ]
