# Generated by Django 5.2.13 on 2026-09-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_batch_start_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='address',
            field=models.TextField(blank=True, help_text='Billing address, one line per line. Printed as-is.'),
        ),
        migrations.AddField(
            model_name='institute',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='institute',
            name='gstin',
            field=models.CharField(blank=True, help_text='Printed on receipts. Blank = the GSTIN line is omitted.', max_length=20),
        ),
        migrations.AddField(
            model_name='institute',
            name='letterhead_title',
            field=models.CharField(blank=True, help_text="Line above the address block, e.g. 'Corporate Center'.", max_length=80),
        ),
        migrations.AddField(
            model_name='institute',
            name='payee_name',
            field=models.CharField(blank=True, help_text="Legal entity cheques/DDs are drawn in favour of — e.g. 'JD Educational Trust'. Blank falls back to the institute name.", max_length=160),
        ),
        migrations.AddField(
            model_name='institute',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
