# Generated by Django 5.2.13 on 2026-09-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_institute_address_institute_email_institute_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='letterhead_placement',
            field=models.CharField(choices=[('LEFT', 'Under the logo, left-aligned'), ('RIGHT', 'Opposite the logo, right-aligned')], default='LEFT', help_text="Which of the two printed stationery layouts this institute uses. LEFT puts the address block under the logo and the undertaking footer at the left margin. RIGHT sets the address opposite the logo, the undertaking footer at the right margin, and — matching the printed JD School of Design receipt — right-aligns the student/father name rows and 'Issued By'.", max_length=5),
        ),
        migrations.AddField(
            model_name='institute',
            name='signature',
            field=models.ImageField(blank=True, help_text="Authorised signatory's signature. Printed in that box on the undertaking; receipts are always left unsigned.", null=True, upload_to='institute/signatures/'),
        ),
    ]
